# Generated by Django 4.2.3 on 2023-07-25 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default.jpg', max_length=200, upload_to='images', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required.', max_length=320, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')], verbose_name='email address'),
        ),
    ]
