# Generated by Django 4.2.3 on 2023-08-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profile_picture_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', max_length=200, upload_to='images', verbose_name='profile image'),
        ),
    ]
