# Generated by Django 4.2.3 on 2023-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=2000, verbose_name='profile bio'),
        ),
    ]
