# Generated by Django 4.2.3 on 2023-08-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_content_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', max_length=200, upload_to='images', verbose_name='recipe image'),
        ),
    ]
